# CMakeInstallDirs.cmake
#
# Standard installation directories as with autotools, definable by user
# The first are reletive to prefix, to use with install command; the second are absolute paths
# 
# This module defines the following variables:
#	Relational to prefix path:
#	CMAKE_INSTALL_BINDIR			- user executables (bin)
#	CMAKE_INSTALL_SBINDIR			- system admin executables (sbin)
#	CMAKE_INSTALL_LIBEXECDIR		- program executables (libexec)
#	CMAKE_INSTALL_SYSCONFDIR		- read-only single-machine data (etc)
#	CMAKE_INSTALL_SHAREDSTATEDIR		- modifiable architecture-independent data (com)
#	CMAKE_INSTALL_LOCALSTATEDIR		- modifiable single-machine data (var)
#	CMAKE_INSTALL_LIBDIR			- object code libraries (lib)
#	CMAKE_INSTALL_INCLUDEDIR		- C header files (include)
#	CMAKE_INSTALL_OLDINCLUDEDIR		- C header files for non-gcc (/usr/include)
#	CMAKE_INSTALL_DATAROOTDIR		- read-only architecture-independent data root (share)
#	CMAKE_INSTALL_DATADIR			- read-only architecture-independent data (DATAROOTDIR)
#	CMAKE_INSTALL_INFODIR			- info documentation (DATAROOTDIR/info)
#	CMAKE_INSTALL_LOCALEDIR			- locale-dependent data (DATAROOTDIR/locale)
#	CMAKE_INSTALL_MANDIR			- man documentation (DATAROOTDIR/man)
#	CMAKE_INSTALL_DOCDIR			- documentation root (DATAROOTDIR/doc)
#
#	Full path with the prefix prepended, if exist:
#	CMAKE_INSTALL_FULL_BINDIR		- user executables full path (PREFIX/BINDIR)
#	CMAKE_INSTALL_FULL_SBINDIR		- system admin executables full path (PREFIX/SBINDIR)
#	CMAKE_INSTALL_FULL_LIBEXECDIR		- program executables full path (PREFIX/LIBEXECDIR)
#	CMAKE_INSTALL_FULL_SYSCONFDIR		- read-only single-machine data fill path (PREFIX/SYSCONFDIR)
#	CMAKE_INSTALL_FULL_SHAREDSTATEDIR	- modifiable architecture-independent data full path (PREFIX/SHAREDSTATEDIR)
#	CMAKE_INSTALL_FULL_LOCALSTATEDIR	- modifiable single-machine data full path (PREFIX/LOCALSTATEDIR)
#	CMAKE_INSTALL_FULL_LIBDIR		- object code libraries full path (PREFIX/LIBDIR)
#	CMAKE_INSTALL_FULL_INCLUDEDIR		- C header files full path (PREFIX/INCLUDEDIR)
#	CMAKE_INSTALL_FULL_OLDINCLUDEDIR	- C header files for non-gcc full path (/usr/include)
#	CMAKE_INSTALL_FULL_DATAROOTDIR		- read-only architecture-independent data root full path (PREFIX/DATAROOTDIR)
#	CMAKE_INSTALL_FULL_DATADIR		- read-only architecture-independent data full path (PREFIX/DATADIR)
#	CMAKE_INSTALL_FULL_INFODIR		- info documentation full path (PREFIX/INFODIR)
#	CMAKE_INSTALL_FULL_LOCALEDIR		- locale-dependent data full path (PREFIX/LOCALEDIR)
#	CMAKE_INSTALL_FULL_MANDIR		- man documentation full path (PREFIX/MANDIR)
#	CMAKE_INSTALL_FULL_DOCDIR		- documentation root full path (PREFIX/DOCDIR)
#
#=============================================================================
# Copyright (c) 2011 Nikita Krupen'ko <krnekit@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
# * Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#=============================================================================

# Set the variable, if it hasn't defined by user
#
if(NOT DEFINED CMAKE_INSTALL_BINDIR)
	set(CMAKE_INSTALL_BINDIR "bin" CACHE PATH "user executables (bin)")
endif(NOT DEFINED CMAKE_INSTALL_BINDIR)

if(NOT DEFINED CMAKE_INSTALL_SBINDIR)
	set(CMAKE_INSTALL_SBINDIR "sbin" CACHE PATH "system admin executables (sbin)")
endif(NOT DEFINED CMAKE_INSTALL_SBINDIR)

if(NOT DEFINED CMAKE_INSTALL_LIBEXECDIR)
	set(CMAKE_INSTALL_LIBEXECDIR "libexec" CACHE PATH "program executables (libexec)")
endif(NOT DEFINED CMAKE_INSTALL_LIBEXECDIR)

if(NOT DEFINED CMAKE_INSTALL_SYSCONFDIR)
	set(CMAKE_INSTALL_SYSCONFDIR "etc" CACHE PATH "read-only single-machine data (etc)")
endif(NOT DEFINED CMAKE_INSTALL_SYSCONFDIR)

if(NOT DEFINED CMAKE_INSTALL_SHAREDSTATEDIR)
	set(CMAKE_INSTALL_SHAREDSTATEDIR "com" CACHE PATH "modifiable architecture-independent data (com)")
endif(NOT DEFINED CMAKE_INSTALL_SHAREDSTATEDIR)

if(NOT DEFINED CMAKE_INSTALL_LOCALSTATEDIR)
	set(CMAKE_INSTALL_LOCALSTATEDIR "var" CACHE PATH "modifiable single-machine data (var)")
endif(NOT DEFINED CMAKE_INSTALL_LOCALSTATEDIR)

if(NOT DEFINED CMAKE_INSTALL_LIBDIR)
	set(CMAKE_INSTALL_LIBDIR "lib" CACHE PATH "object code libraries (lib)")
endif(NOT DEFINED CMAKE_INSTALL_LIBDIR)

if(NOT DEFINED CMAKE_INSTALL_INCLUDEDIR)
	set(CMAKE_INSTALL_INCLUDEDIR "include" CACHE PATH "C header files (include)")
endif(NOT DEFINED CMAKE_INSTALL_INCLUDEDIR)

if(NOT DEFINED CMAKE_INSTALL_OLDINCLUDEDIR)
	set(CMAKE_INSTALL_OLDINCLUDEDIR "/usr/include" CACHE PATH "C header files for non-gcc (/usr/include)")
endif(NOT DEFINED CMAKE_INSTALL_OLDINCLUDEDIR)

if(NOT DEFINED CMAKE_INSTALL_DATAROOTDIR)
	set(CMAKE_INSTALL_DATAROOTDIR "share" CACHE PATH "read-only architecture-independent data root (share)")
endif(NOT DEFINED CMAKE_INSTALL_DATAROOTDIR)

if(NOT DEFINED CMAKE_INSTALL_DATADIR)
	set(CMAKE_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}" CACHE PATH "read-only architecture-independent data (DATAROOTDIR)")
endif(NOT DEFINED CMAKE_INSTALL_DATADIR)

if(NOT DEFINED CMAKE_INSTALL_INFODIR)
	set(CMAKE_INSTALL_INFODIR "${CMAKE_INSTALL_DATAROOTDIR}/info" CACHE PATH "info documentation (DATAROOTDIR/info)")
endif(NOT DEFINED CMAKE_INSTALL_INFODIR)

if(NOT DEFINED CMAKE_INSTALL_LOCALEDIR)
	set(CMAKE_INSTALL_LOCALEDIR "${CMAKE_INSTALL_DATAROOTDIR}/locale" CACHE PATH "locale-dependent data (DATAROOTDIR/locale)")
endif(NOT DEFINED CMAKE_INSTALL_LOCALEDIR)

if(NOT DEFINED CMAKE_INSTALL_MANDIR)
	set(CMAKE_INSTALL_MANDIR "${CMAKE_INSTALL_DATAROOTDIR}/man" CACHE PATH "man documentation (DATAROOTDIR/man)")
endif(NOT DEFINED CMAKE_INSTALL_MANDIR)

if(NOT DEFINED CMAKE_INSTALL_DOCDIR)
	set(CMAKE_INSTALL_DOCDIR "${CMAKE_INSTALL_DATAROOTDIR}/doc" CACHE PATH "documentation root (DATAROOTDIR/doc)")
endif(NOT DEFINED CMAKE_INSTALL_DOCDIR)

mark_as_advanced(
	CMAKE_INSTALL_BINDIR
	CMAKE_INSTALL_SBINDIR
	CMAKE_INSTALL_LIBEXECDIR
	CMAKE_INSTALL_SYSCONFDIR
	CMAKE_INSTALL_SHAREDSTATEDIR
	CMAKE_INSTALL_LOCALSTATEDIR
	CMAKE_INSTALL_LIBDIR
	CMAKE_INSTALL_INCLUDEDIR
	CMAKE_INSTALL_OLDINCLUDEDIR
	CMAKE_INSTALL_DATAROOTDIR
	CMAKE_INSTALL_DATADIR
	CMAKE_INSTALL_INFODIR
	CMAKE_INSTALL_LOCALEDIR
	CMAKE_INSTALL_MANDIR
	CMAKE_INSTALL_DOCDIR
)

# Make the full path and store it to corresponding variable
#
if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_BINDIR})
	set(CMAKE_INSTALL_FULL_BINDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}" CACHE PATH "user executables full path (PREFIX/BINDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_BINDIR})
	set(CMAKE_INSTALL_FULL_BINDIR "${CMAKE_INSTALL_BINDIR}" CACHE PATH "user executables full path (PREFIX/BINDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_BINDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_SBINDIR})
	set(CMAKE_INSTALL_FULL_SBINDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_SBINDIR}" CACHE PATH "system admin executables full path (PREFIX/SBINDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_SBINDIR})
	set(CMAKE_INSTALL_FULL_SBINDIR "${CMAKE_INSTALL_SBINDIR}" CACHE PATH "system admin executables full path (PREFIX/SBINDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_SBINDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LIBEXECDIR})
	set(CMAKE_INSTALL_FULL_LIBEXECDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBEXECDIR}" CACHE PATH "program executables full path (PREFIX/LIBEXECDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LIBEXECDIR})
	set(CMAKE_INSTALL_FULL_LIBEXECDIR "${CMAKE_INSTALL_LIBEXECDIR}" CACHE PATH "program executables full path (PREFIX/LIBEXECDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LIBEXECDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_SYSCONFDIR})
	set(CMAKE_INSTALL_FULL_SYSCONFDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_SYSCONFDIR}" CACHE PATH "read-only single-machine data fill path (PREFIX/SYSCONFDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_SYSCONFDIR})
	set(CMAKE_INSTALL_FULL_SYSCONFDIR "${CMAKE_INSTALL_SYSCONFDIR}" CACHE PATH "read-only single-machine data fill path (PREFIX/SYSCONFDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_SYSCONFDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_SHAREDSTATEDIR})
	set(CMAKE_INSTALL_FULL_SHAREDSTATEDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_SHAREDSTATEDIR}" CACHE PATH "modifiable architecture-independent data full path (PREFIX/SHAREDSTATEDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_SHAREDSTATEDIR})
	set(CMAKE_INSTALL_FULL_SHAREDSTATEDIR "${CMAKE_INSTALL_SHAREDSTATEDIR}" CACHE PATH "modifiable architecture-independent data full path (PREFIX/SHAREDSTATEDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_SHAREDSTATEDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LOCALSTATEDIR})
	set(CMAKE_INSTALL_FULL_LOCALSTATEDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LOCALSTATEDIR}" CACHE PATH "modifiable single-machine data full path (PREFIX/LOCALSTATEDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LOCALSTATEDIR})
	set(CMAKE_INSTALL_FULL_LOCALSTATEDIR "${CMAKE_INSTALL_LOCALSTATEDIR}" CACHE PATH "modifiable single-machine data full path (PREFIX/LOCALSTATEDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LOCALSTATEDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LIBDIR})
	set(CMAKE_INSTALL_FULL_LIBDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}" CACHE PATH "object code libraries full path (PREFIX/LIBDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LIBDIR})
	set(CMAKE_INSTALL_FULL_LIBDIR "${CMAKE_INSTALL_LIBDIR}" CACHE PATH "object code libraries full path (PREFIX/LIBDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LIBDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_INCLUDEDIR})
	set(CMAKE_INSTALL_FULL_INCLUDEDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_INCLUDEDIR}" CACHE PATH "C header files full path (PREFIX/INCLUDEDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_INCLUDEDIR})
	set(CMAKE_INSTALL_FULL_INCLUDEDIR "${CMAKE_INSTALL_INCLUDEDIR}" CACHE PATH "C header files full path (PREFIX/INCLUDEDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_INCLUDEDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_OLDINCLUDEDIR})
	set(CMAKE_INSTALL_FULL_OLDINCLUDEDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_OLDINCLUDEDIR}" CACHE PATH "C header files for non-gcc full path (/usr/include)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_OLDINCLUDEDIR)
	set(CMAKE_INSTALL_FULL_OLDINCLUDEDIR "${CMAKE_INSTALL_OLDINCLUDEDIR}" CACHE PATH "C header files for non-gcc full path (/usr/include)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_OLDINCLUDEDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_DATAROOTDIR})
	set(CMAKE_INSTALL_FULL_DATAROOTDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATAROOTDIR}" CACHE PATH "read-only architecture-independent data root full path (PREFIX/DATAROOTDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_DATAROOTDIR})
	set(CMAKE_INSTALL_FULL_DATAROOTDIR "${CMAKE_INSTALL_DATAROOTDIR}" CACHE PATH "read-only architecture-independent data root full path (PREFIX/DATAROOTDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_DATAROOTDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_DATADIR})
	set(CMAKE_INSTALL_FULL_DATADIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATADIR}" CACHE PATH "read-only architecture-independent data full path (PREFIX/DATADIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_DATADIR})
	set(CMAKE_INSTALL_FULL_DATADIR "${CMAKE_INSTALL_DATADIR}" CACHE PATH "read-only architecture-independent data full path (PREFIX/DATADIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_DATADIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_INFODIR})
	set(CMAKE_INSTALL_FULL_INFODIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_INFODIR}" CACHE PATH "info documentation full path (PREFIX/INFODIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_INFODIR})
	set(CMAKE_INSTALL_FULL_INFODIR "${CMAKE_INSTALL_INFODIR}" CACHE PATH "info documentation full path (PREFIX/INFODIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_INFODIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LOCALEDIR})
	set(CMAKE_INSTALL_FULL_LOCALEDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LOCALEDIR}" CACHE PATH "locale-dependent data full path (PREFIX/LOCALEDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LOCALEDIR})
	set(CMAKE_INSTALL_FULL_LOCALEDIR "${CMAKE_INSTALL_LOCALEDIR}" CACHE PATH "locale-dependent data full path (PREFIX/LOCALEDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_LOCALEDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_MANDIR})
	set(CMAKE_INSTALL_FULL_MANDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_MANDIR}" CACHE PATH "man documentation full path (PREFIX/MANDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_MANDIR})
	set(CMAKE_INSTALL_FULL_MANDIR "${CMAKE_INSTALL_MANDIR}" CACHE PATH "man documentation full path (PREFIX/MANDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_MANDIR})

if(NOT IS_ABSOLUTE ${CMAKE_INSTALL_DOCDIR})
	set(CMAKE_INSTALL_FULL_DOCDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DOCDIR}" CACHE PATH "documentation root full path (PREFIX/DOCDIR)")
else(NOT IS_ABSOLUTE ${CMAKE_INSTALL_DOCDIR})
	set(CMAKE_INSTALL_FULL_DOCDIR "${CMAKE_INSTALL_DOCDIR}" CACHE PATH "documentation root full path (PREFIX/DOCDIR)")
endif(NOT IS_ABSOLUTE ${CMAKE_INSTALL_DOCDIR})

mark_as_advanced(
	CMAKE_INSTALL_FULL_BINDIR
	CMAKE_INSTALL_FULL_SBINDIR
	CMAKE_INSTALL_FULL_LIBEXECDIR
	CMAKE_INSTALL_FULL_SYSCONFDIR
	CMAKE_INSTALL_FULL_SHAREDSTATEDIR
	CMAKE_INSTALL_FULL_LOCALSTATEDIR
	CMAKE_INSTALL_FULL_LIBDIR
	CMAKE_INSTALL_FULL_INCLUDEDIR
	CMAKE_INSTALL_FULL_OLDINCLUDEDIR
	CMAKE_INSTALL_FULL_DATAROOTDIR
	CMAKE_INSTALL_FULL_DATADIR
	CMAKE_INSTALL_FULL_INFODIR
	CMAKE_INSTALL_FULL_LOCALEDIR
	CMAKE_INSTALL_FULL_MANDIR
	CMAKE_INSTALL_FULL_DOCDIR
)
